input {
  beats {
    port => 5044
  }
}

filter {
  if [log][file][path] =~ "auth" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{DATA:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:message}" }
      overwrite => [ "message" ]
    }
    mutate {
      add_tag => ["auth_log"]
    }
  }

  if [log][file][path] =~ "syslog" {
    mutate {
      add_tag => ["syslog"]
    }
  }

  date {
    match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "linux-logs-%{+YYYY.MM.dd}"
  }
}
